// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"babyduck/token"
)

const (
	NoState    = -1
	NumStates  = 69
	NumSymbols = 84
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '-'
1: '.'
2: '''
3: '''
4: 'p'
5: 'r'
6: 'o'
7: 'g'
8: 'r'
9: 'a'
10: 'm'
11: ';'
12: 'm'
13: 'a'
14: 'i'
15: 'n'
16: 'e'
17: 'n'
18: 'd'
19: 'v'
20: 'a'
21: 'r'
22: ':'
23: ','
24: 'i'
25: 'n'
26: 't'
27: 'f'
28: 'l'
29: 'o'
30: 'a'
31: 't'
32: 'v'
33: 'o'
34: 'i'
35: 'd'
36: '('
37: ')'
38: '{'
39: '}'
40: '='
41: '<'
42: '>'
43: '!'
44: '='
45: '+'
46: '-'
47: '*'
48: '/'
49: 'p'
50: 'r'
51: 'i'
52: 'n'
53: 't'
54: 'w'
55: 'h'
56: 'i'
57: 'l'
58: 'e'
59: 'd'
60: 'o'
61: 'i'
62: 'f'
63: 'e'
64: 'l'
65: 's'
66: 'e'
67: ' '
68: '\t'
69: '\r'
70: '\n'
71: '*'
72: '*'
73: '*'
74: '*'
75: 'a'-'z'
76: 'a'-'z'
77: '0'-'9'
78: '0'-'9'
79: '0'-'9'
80: '0'-'9'
81: '0'-'9'
82: '0'-'9'
83: .
*/
